
number = int(input("How many tasks do you want to do? ")) 
if number == 1:
  input("What is the first task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
elif number == 2:
  input("What is the first task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the second task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
elif number == 3:
  input("What is the first task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the second task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the third task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
elif number == 4:
  input("What is the first task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the second task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the third task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the fourth task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
elif number == 5:
  input("What is the first task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the second task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the third task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the fourth task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the fifth task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
elif number == 6:
  input("What is the first task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the second task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the third task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the fourth task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the fifth task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
  input("What is the sixth task you want to do? ")
  input("How many minutes do you want to spend on that task? ")
elif number > 6:
  print("The number you entered is to many tasks to do at once")
else:
  print("You entered a negative number, you can't have a negative tasks ")
